name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            filename: hexfile
          - os: macos-latest
            filename: hexfile
          - os: windows-latest
            filename: hexfile.exe
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Build
      run: go build -v .
    - name: Publish Release
      uses: softprops/action-gh-release@v1
      with: 
        files: ${{ matrix.filename }}
